
package frames;

import dao.PedidoDAO;
import estructuras.PilaProductos;
import java.awt.Dimension; 
import java.awt.Color;
import java.sql.Connection;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import objetos.Productos;
import services.DataBase;
import services.SesionService;

public class MenuV extends javax.swing.JFrame {
    private int idEmpleado;
    private PedidoDAO pedidoDAO;
    private PilaProductos pilaProductos;
    private Connection connection;
    
    
    public MenuV(int idEmpleado, Connection connection) {
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setLocationRelativeTo(null);
        this.idEmpleado = idEmpleado;
        String nombreCompleto = obtenerNombreCompleto(idEmpleado);
        jLabel10.setText(nombreCompleto);
        this.connection = connection;
        this.pedidoDAO= new PedidoDAO(connection);
        this.pilaProductos = new PilaProductos(); 
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jP_nv = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TxtCodigo = new javax.swing.JTextField();
        jComboBoxTallas = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        TxtCantidad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TxtPrecio = new javax.swing.JTextField();
        jP_cli = new javax.swing.JPanel();
        jP_produc = new javax.swing.JPanel();
        jP_vent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cerrar = new javax.swing.JButton();
        minimizar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jP_NuevaVenta = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jP_Clientes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jP_Productos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jP_Ventas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jP_CerrarSesion = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));

        jP_nv.setBackground(new java.awt.Color(182, 215, 248));
        jP_nv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(236, 153, 69));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-buscar-30 (1).png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jP_nv.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 40, 40));

        jButton2.setBackground(new java.awt.Color(236, 153, 69));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-guardar.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jP_nv.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 40, 40));

        jButton3.setBackground(new java.awt.Color(236, 153, 69));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-eliminar-25.png"))); // NOI18N
        jButton3.setBorder(null);
        jP_nv.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 40, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Talla", "Cantidad", "Precio Unitario"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jP_nv.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 920, 110));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Venta");
        jP_nv.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Codigo:");
        jP_nv.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));
        jP_nv.add(TxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 130, 30));

        jComboBoxTallas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "L" }));
        jP_nv.add(jComboBoxTallas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 90, 30));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Tallas:");
        jP_nv.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));
        jP_nv.add(TxtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 120, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Cantidad:");
        jP_nv.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        jLabel15.setText("Nueva Venta");
        jP_nv.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 100, 30));
        jP_nv.add(TxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 120, 30));

        jPanel2.add(jP_nv);

        jP_cli.setBackground(new java.awt.Color(255, 204, 153));
        jP_cli.setPreferredSize(new java.awt.Dimension(980, 564));

        javax.swing.GroupLayout jP_cliLayout = new javax.swing.GroupLayout(jP_cli);
        jP_cli.setLayout(jP_cliLayout);
        jP_cliLayout.setHorizontalGroup(
            jP_cliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        jP_cliLayout.setVerticalGroup(
            jP_cliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jPanel2.add(jP_cli);

        jP_produc.setBackground(new java.awt.Color(255, 255, 204));
        jP_produc.setPreferredSize(new java.awt.Dimension(980, 564));

        javax.swing.GroupLayout jP_producLayout = new javax.swing.GroupLayout(jP_produc);
        jP_produc.setLayout(jP_producLayout);
        jP_producLayout.setHorizontalGroup(
            jP_producLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jP_producLayout.setVerticalGroup(
            jP_producLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jPanel2.add(jP_produc);

        jP_vent.setBackground(new java.awt.Color(165, 207, 246));
        jP_vent.setPreferredSize(new java.awt.Dimension(980, 564));

        javax.swing.GroupLayout jP_ventLayout = new javax.swing.GroupLayout(jP_vent);
        jP_vent.setLayout(jP_ventLayout);
        jP_ventLayout.setHorizontalGroup(
            jP_ventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jP_ventLayout.setVerticalGroup(
            jP_ventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jPanel2.add(jP_vent);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 980, 570));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 110));

        cerrar.setBackground(new java.awt.Color(243, 112, 24));
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-cerrar-ventana-32.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, 30, 30));

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-menos-32.png"))); // NOI18N
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        getContentPane().add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1121, 10, 30, 30));

        jLabel8.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Bienvenido ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 160, 40));

        jLabel10.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("trabajador");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 160, 40));

        jP_NuevaVenta.setBackground(new java.awt.Color(236, 153, 69));
        jP_NuevaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_NuevaVentaMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-agregar-a-carrito-de-compras-30.png"))); // NOI18N
        jLabel3.setText("Nueva Venta");

        javax.swing.GroupLayout jP_NuevaVentaLayout = new javax.swing.GroupLayout(jP_NuevaVenta);
        jP_NuevaVenta.setLayout(jP_NuevaVentaLayout);
        jP_NuevaVentaLayout.setHorizontalGroup(
            jP_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_NuevaVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_NuevaVentaLayout.setVerticalGroup(
            jP_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_NuevaVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jP_NuevaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 183, -1));

        jP_Clientes.setBackground(new java.awt.Color(236, 153, 69));
        jP_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_ClientesMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-clientes-30.png"))); // NOI18N
        jLabel4.setText("Clientes");

        javax.swing.GroupLayout jP_ClientesLayout = new javax.swing.GroupLayout(jP_Clientes);
        jP_Clientes.setLayout(jP_ClientesLayout);
        jP_ClientesLayout.setHorizontalGroup(
            jP_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_ClientesLayout.setVerticalGroup(
            jP_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jP_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 183, -1));

        jP_Productos.setBackground(new java.awt.Color(236, 153, 69));
        jP_Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_ProductosMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-productos-30.png"))); // NOI18N
        jLabel5.setText("Productos");

        javax.swing.GroupLayout jP_ProductosLayout = new javax.swing.GroupLayout(jP_Productos);
        jP_Productos.setLayout(jP_ProductosLayout);
        jP_ProductosLayout.setHorizontalGroup(
            jP_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_ProductosLayout.setVerticalGroup(
            jP_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jP_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 183, -1));

        jP_Ventas.setBackground(new java.awt.Color(236, 153, 69));
        jP_Ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_VentasMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-ventas-30.png"))); // NOI18N
        jLabel6.setText("Ventas");

        javax.swing.GroupLayout jP_VentasLayout = new javax.swing.GroupLayout(jP_Ventas);
        jP_Ventas.setLayout(jP_VentasLayout);
        jP_VentasLayout.setHorizontalGroup(
            jP_VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_VentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_VentasLayout.setVerticalGroup(
            jP_VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_VentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jP_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 183, -1));

        jP_CerrarSesion.setBackground(new java.awt.Color(236, 153, 69));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-cerrar-sesión-30.png"))); // NOI18N
        jLabel7.setText("Cerrar Sesión");

        javax.swing.GroupLayout jP_CerrarSesionLayout = new javax.swing.GroupLayout(jP_CerrarSesion);
        jP_CerrarSesion.setLayout(jP_CerrarSesionLayout);
        jP_CerrarSesionLayout.setHorizontalGroup(
            jP_CerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_CerrarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_CerrarSesionLayout.setVerticalGroup(
            jP_CerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_CerrarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jP_CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, -1));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondomenu.png"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1210, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setState(MenuV.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_cerrarMouseClicked

    private void jP_NuevaVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_NuevaVentaMouseClicked
        jP_nv.setVisible(true);
        jP_cli.setVisible(false);
        jP_produc.setVisible(false);
        jP_vent.setVisible(false);
        jP_NuevaVenta.setBackground(Color.black);
        jP_Clientes.setBackground(new Color(236,153,69));
        jP_Productos.setBackground(new Color(236,153,69));
        jP_Ventas.setBackground(new Color(236,153,69));
    }//GEN-LAST:event_jP_NuevaVentaMouseClicked

    private void jP_ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_ClientesMouseClicked
        jP_cli.setVisible(true);
        jP_nv.setVisible(false);
        jP_produc.setVisible(false);
        jP_vent.setVisible(false);
        jP_Clientes.setBackground(Color.black);
        jP_NuevaVenta.setBackground(new Color(236,153,69));
        jP_Productos.setBackground(new Color(236,153,69));
        jP_Ventas.setBackground(new Color(236,153,69));
    }//GEN-LAST:event_jP_ClientesMouseClicked

    private void jP_ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_ProductosMouseClicked
        jP_produc.setVisible(true);
        jP_cli.setVisible(false);
        jP_nv.setVisible(false);
        jP_vent.setVisible(false);
        jP_Productos.setBackground(Color.black);
        jP_Clientes.setBackground(new Color(236,153,69));
        jP_NuevaVenta.setBackground(new Color(236,153,69));
        jP_Ventas.setBackground(new Color(236,153,69));
    }//GEN-LAST:event_jP_ProductosMouseClicked

    private void jP_VentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_VentasMouseClicked
        jP_vent.setVisible(true);
        jP_cli.setVisible(false);
        jP_produc.setVisible(false);
        jP_nv.setVisible(false);
        jP_Ventas.setBackground(Color.black);
        jP_Clientes.setBackground(new Color(236,153,69));
        jP_Productos.setBackground(new Color(236,153,69));
        jP_NuevaVenta.setBackground(new Color(236,153,69));
    }//GEN-LAST:event_jP_VentasMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // Obtener el código ingresado en el JTextField
        String codigo = TxtCodigo.getText();
        
        // Crear un objeto Productos con el código ingresado
        Productos producto = new Productos(codigo, null, null, null, 0,0.0 , connection);
        
        // Obtener las tallas disponibles para el producto
        List<String> tallasDisponibles = producto.encontrarTallas(pedidoDAO); // Pasa la instancia de pedidoDAO
        
        // Actualizar el JComboBox con las tallas encontradas
        actualizarComboBoxTallas(tallasDisponibles);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // Obtener los valores de los campos TxtCodigo, TxtCantidad y jComboBoxTallas
    String codigo = TxtCodigo.getText();
    String cantidadStr = TxtCantidad.getText();
    int cantidad = Integer.parseInt(cantidadStr); // Convertir la cantidad a entero
    String talla = (String) jComboBoxTallas.getSelectedItem(); // Obtener la talla seleccionada
    Double precio = Double.parseDouble(TxtPrecio.getText());
    // Crear un nuevo producto con los valores obtenidos
    Productos nuevoProducto = new Productos(codigo, "Predeterminado", "Predeterminado", Collections.singletonList(talla), cantidad, precio, connection);

    pilaProductos.agregarProducto(nuevoProducto); // Agregar el nuevo producto a la pila

    // Mostrar los productos en la tabla
    mostrarProductosEnTabla();


    }//GEN-LAST:event_jButton2ActionPerformed
   private void mostrarProductosEnTabla() {
        // Crear un modelo de tabla
        DefaultTableModel model = new DefaultTableModel();
        // Agregar las columnas a la tabla
        model.addColumn("Código");
        model.addColumn("Nombre");
        model.addColumn("Descripción");
        model.addColumn("Talla");
        model.addColumn("Cantidad");
        model.addColumn("Precio Unitario");

        // Recorrer la pila de productos y agregar cada producto a la tabla
        for (Productos producto : pilaProductos.getPilaProductos()) {
            // Convertir la lista de tallas a una cadena separada por comas
            String tallas = String.join(", ", producto.getTallas());

            // Agregar una fila a la tabla con los datos del producto
            model.addRow(new Object[]{
                producto.getCodigo(),
                producto.getNombre(),
                producto.getDescripcion(),
                tallas,
                producto.getCantidad(),
                producto.getPrecio()
            });
        }

        // Establecer el modelo de la tabla
        jTable1.setModel(model);
    }
// Método para actualizar los items del JComboBox con las tallas encontradas
    private void actualizarComboBoxTallas(List<String> tallas) {
        jComboBoxTallas.removeAllItems(); // Limpiar todos los items actuales del JComboBox

    // Agregar las nuevas tallas al JComboBox
        for (String talla : tallas) {
            jComboBoxTallas.addItem(talla);
        }
    }
    /**
     * @param args the command line arguments
     */
    private String obtenerNombreCompleto(int idEmpleado) {
        SesionService sesionService = new SesionService(DataBase.conectar()); // Aquí puedes obtener la conexión según tu implementación
        return sesionService.obtenerNombreYApellidos(idEmpleado);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtCantidad;
    private javax.swing.JTextField TxtCodigo;
    private javax.swing.JTextField TxtPrecio;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxTallas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jP_CerrarSesion;
    private javax.swing.JPanel jP_Clientes;
    private javax.swing.JPanel jP_NuevaVenta;
    private javax.swing.JPanel jP_Productos;
    private javax.swing.JPanel jP_Ventas;
    private javax.swing.JPanel jP_cli;
    private javax.swing.JPanel jP_nv;
    private javax.swing.JPanel jP_produc;
    private javax.swing.JPanel jP_vent;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel minimizar;
    // End of variables declaration//GEN-END:variables
}
